repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--filter-files"]
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--safe]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            args: ["--config=.flake8"]
            additional_dependencies: ['flake8-bugbear==21.4.3']
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          -   id: mypy